# Generated by Django 3.2 on 2022-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
